### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by autuas** [tjouni/messageboard#1]
*Projekti ladattu 21.8. klo 10.30*

#### Sovellus Herokussa

Normaalikäyttäjän käyttötapaukset toimivat suurelta osin hyvin, joskin normaalikäyttäjällä on myös admin-oikeuksia:
- Rekisteröityminen, listaus, viestien katsominen, uusien ketjujen luominen ja vanhoihin vastaaminen onnistuvat hyvin
- Viestien ja käyttäjien poistaminen onnistuu myös muiden käyttäjien osalta, mutta viestien muokkaaminen ei ole mahdollista
- Samalla käyttäjänimellä voi rekisteröityä useamman kerran
- Itse web-sovelluksen ulkoasu on selkeä ja miellyttävä

#### Koodi

Esittelytekstissä mainittu kategoriaominaisuus ei vielä ole käytössä, mutta se sisältyy ohjelmakoodiin tietokantakaavion mukaisesti. Koodi on kauttaaltaan siistiä ja tarkoituksenmukaista. Vaikka koodia ei ole kommentoitu, on sitä nimeämiskäytännön loogisuuden vuoksi helppo lukea. Kansio- ja tiedostorakenne on kurssin esimerkkisovelluksen kaltainen.

**Comment by tjouni** [comment]
> Samalla käyttäjänimellä voi rekisteröityä useamman kerran
En saanut itse rekisteröityä käyttäjää useampaan kertaan. Voi olla että herokussa oli vielä eilen vanha tietokanta. Pitäisi nyt toimia oikein.

> Viestien ja käyttäjien poistaminen onnistuu myös muiden käyttäjien osalta, mutta viestien muokkaaminen ei ole mahdollista
Lisätty viestien muokkausmahdollisuus
