### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ilmari666** [tjouni/messageboard#2]
Ladattu projekti Ke 4.9. klo 9:40

Lokaalitestaus käyttöohjeiden seuraamisen jälkeen:
Käyttäjän luominen ja poistaminen onnistuu.
Uusien viestisäikeiden luominen ei onnistu, ilmeisesti kategorioiden puutteen takia.
Kun admin rooli on luotu kantaan ja allokoitu käyttäjälle
huomataan että "Category management"-tabi on ilmestynt näkyviin sekä toinen "List users" joka vaikuttaa duplikaatilta kuin myös normaalikäyttäjälle näkyvä. Nyt siis ylävalikossa näkyy kaksi "List users"-täppää.
Category management tarjoaa mahdollisuuden muokata ja poistaa default kategoria jota dropdown ei kuitenkaan tarjoa.
Kun kantaan lisää kategorian se ilmestyy category management-listauksen alle ja sitä voi muokata tai poistaa. Tämä ei valitettavasti silti näy uuden säikeen luomisessa joten uutta säiettä ei voinut testitilanteessa luoda eikä sovellus tarjonnut käyttäjälle palautetta miksi viestin luonti epäonnistui.

Herokuun deployattu versio kuitenkin näyttää toimivan käyttötapausten mukaisesti, kuitenkin niin että List Users näkyy kahteen kertaan adminille yläpalkissa. 
Virheellisesti täytetyt lomakkeet eivät kaataneet sovellusta mutteivät myöskään antaneet virheviestejä.

Selkeä dokumentaatio.
Kantakaavio ja rakenne on hyvä ja selkeä sekä vastaa ongelmaan.

Plussaa:
Metodeja kuvattu pythonisesti
Salasanat hashatty

**Comment by tjouni** [comment]
Korjattu asennukseen liittyvä kategorian puute lisäämällä sovelluksen käynnistysvaiheeseen default-kategorian luonti tarvittaessa.

Virheviestien puuttumista en onnistunut toistamaan, minun selaimellani virheellisesti täytetyt kentät kyllä näyttävät kentän vieressä virheilmoituksen.

Muut ongelmat liittyivät siihen, että olin lisäämässä sovellukseen uutta toiminnallisuutta ja kaikki ei toiminut ihan odotetulla tavalla.
